### ISSUE TITLE
Icons appear dark when not in dark mode

### ISSUE THREAD

**Issue by gordoncc** [urbit/developers.urbit.org#114]
<img width="786" alt="icons" src="https://user-images.githubusercontent.com/364577/184994902-53102dbb-8f68-4fa9-b221-b03f10266994.png">

**Comment by matildepark** [comment]
Would it be better if they were always white? (I don't think it looks all that bad like this fwiw). It's that they're mounted at public/images/hoon.svg and using classes to style them doesn't work in there, so we'd have to pick a colour (or invert them selectively and keep the backgrounds as separate elements, basically any way we implement is a pain).
