### ISSUE TITLE
none of the relative links work in hoon school

### ISSUE THREAD

**Issue by nogira** [urbit/developers.urbit.org#152]
i can change them all to work by replacing `./` with `/guides/core/hoon-school/`, but it might be easier to change it in the parser? idk how possible that is tho? lmk if pref just swap to `/guides/core/hoon-school/` and i shall continue doing that

here is an example: https://developers.urbit.org/guides/core/hoon-school/J-stdlib-text
link in first para is `./P-stdlib-io.md` in markdown, but it links to https://developers.urbit.org/guides/P-stdlib-io.md while correct link is https://developers.urbit.org/guides/core/hoon-school/P-stdlib-io.md

also this particular relative link for an image seems to not have a file at all it's pointing to: https://developers.urbit.org/guides/core/hoon-school/binary-tree-tape.png
(on this page https://developers.urbit.org/guides/core/hoon-school/J-stdlib-text#(list-t)-tape )
(and interestingly it's relative link actually gives the correct relative path (`/guides/core/hoon-school/`), so perhaps just need to copy url parsing from `<img>` parsing to `<a>` parsing? )

**Comment by matildepark** [comment]
You should be able to just change `./P-stdlib-io.md` -> `P-stdlib-io`? Hrefs ending in .md won’t resolve; why dot hrefs link to the first dir is sorta confusing me.

**Comment by nogira** [comment]
`P-stdlib-io` doesn't seem to work either

**Comment by nogira** [comment]
`NextLink` component, nor `MarkdownRender` component of foundation-design-system alter the link from `./P-stdlib-io` to `/guides/P-stdlib-io`

i'm not sure where else to look 🙃

**Comment by matildepark** [comment]
I’d just make all the links explicit then as you originally wrote

**Comment by nogira** [comment]
done https://github.com/urbit/developers.urbit.org/pull/155 :)
