### ISSUE TITLE
Images with transparent backgrounds are sometimes illegible in dark theme

### ISSUE THREAD

**Issue by gmcz** [urbit/developers.urbit.org#182]
I'm going through hoon school live and was really tripped up by not noticing the latex formulas as they were nearly invisible. The ASCII chart also suffers this problem. Since there is no dark mode/light mode toggle on the site the only way currently to fix this is by adjusting the browser light/dark mode setting.

Below are screenshots taken from https://developers.urbit.org/guides/core/hoon-school/B-syntax#exercise-making-a-list-from-a-null-terminated-cell showing the issue:

![latex impossible to see](https://user-images.githubusercontent.com/869452/193864636-5ffad218-44a7-4fdb-8404-9c78f23e9deb.png)

![ASCII table illegible in dark mode](https://user-images.githubusercontent.com/869452/193864359-0726cabc-107f-48f9-a707-484adf6b4b7a.png)

This issue may be related to issue #150.

## Some possible solutions

- Add css style to give images a white background
- Add css style to give images a white (or light-grey) background _in dark mode only_
- Update all images with transparent background to non-transparent background

I'm happy to submit a PR to fix this if a maintainer OKs a direction to go.

**Comment by sigilante** [comment]
We have a PR from @matildepark pending soon that will allow native LaTeX/MathJax rendering.  Will that be sensitive to dark mode?

**Comment by gmcz** [comment]
Looks like it's #76, I'll check it out.

**Comment by matildepark** [comment]
It's actually urbit/foundation-design-system#14.

> Will that be sensitive to dark mode?

If we can pass it a class to set colour, then sure. It's a good reminder to go test that out...

As a workaround for now you can wrap the inline HTML here in `{% div class="dark:invert %}` like so:

```
{% div class="dark:invert" %}

<img src="https://latex.codecogs.com/svg.image?\large&space;H(x)=\begin{cases}&space;1,&space;&&space;x&space;>&space;0&space;\\&space;0,&space;&&space;x&space;\le&space;0&space;\end{cases}" title="https://latex.codecogs.com/svg.image?\large H(x):=\begin{cases} 1, & x > 0 \\ 0, & x \le 0 \end{cases}" />

{% /div %}
```

**Comment by gmcz** [comment]
Closed by https://github.com/urbit/foundation-design-system/pull/14 👍🏼
