### ISSUE TITLE
Marks examples has an excessively long quote

### ISSUE THREAD

**Issue by matildepark** [urbit/developers.urbit.org#184]
See all the green — this can't be right, can it? Surely we're missing a `"` somewhere.

https://developers.urbit.org/reference/arvo/clay/marks/examples#libcsvhoon

**Comment by tinnus-napbus** [comment]
it's not missing anything, the syntax highlighter just can't handle escaped double-quotes inside double-quotes. I have tweaked the code to circumvent this syntax highlighter bug

**Comment by matildepark** [comment]
I need to go fix this in prism (unless I already did and we just need to update prism now?)

**Comment by tinnus-napbus** [comment]
oh yeah true, I will reopen. The logic should be "don't count `\"` unless the backslash itself is escaped eg `\\"`". Same logic for single-quotes inside single quotes. Also anything inside `{}`s inside double-quotes should not be counted unless the `{` is escaped

**Comment by matildepark** [comment]
Yeah, I [definitely fixed this upstream](https://github.com/PrismJS/prism/pull/3473), I need to go look at versioning in FDS and see if we just pull prism again.

**Comment by matildepark** [comment]
Upstream pushed the escaped string fix in 1.29.0, which released in August. We were using 1.28.0 in FDS and on our sites, which released in April. I have bumped the version in both FDS and on developers.urbit.org, which should alleviate this in future.
