### ISSUE TITLE
Incomplete Sentence in ` developers.urbit.org/content/reference/hoon/advanced.md `

### ISSUE THREAD

**Issue by IanDCarroll** [urbit/developers.urbit.org#191]
Friendly note :)

in [developers.urbit.org](https://github.com/urbit/developers.urbit.org)/[content](https://github.com/urbit/developers.urbit.org/tree/main/content)/[reference](https://github.com/urbit/developers.urbit.org/tree/main/content/reference)/[hoon](https://github.com/urbit/developers.urbit.org/tree/main/content/reference/hoon)/[advanced.md](https://github.com/urbit/developers.urbit.org/tree/main/content/reference/hoon/advanced.md)

Theres a sentence that doesn't appear to end:  
`If cores never changed, we wouldn't need polymorphism. Of course, nouns are immutable and never change, but we use them as` ... as what? Also there's no period here which really makes me think this sentence should have been longer but got lost in the revision shuffle.

Hope this is helpful.

**Comment by sigilante** [comment]
"but we use them as templates to construct new nouns around."

Corrected :)
