### ISSUE TITLE
Suggest node (engine) version in README and package.json

### ISSUE THREAD

**Issue by netpoetica** [urbit/developers.urbit.org#235]
After original clone, I was using node 12 and encountered a lot of errors. nvm installed node 19 and it went smooth. Recommend listing nodejs and npm version in the README or a CONTRIBUTING.md file; should also be specified in package.json. 

See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

**Comment by matildepark** [comment]
Node 14 is probably best.
