### ISSUE TITLE
Add beak to glossary

### ISSUE THREAD

**Issue by sigilante** [urbit/developers.urbit.org#243]

**Comment by sigilante** [comment]
Alternatively, @matildepark @gordoncc can we add this to the search keywords?  It doesn't show up when searching but it is in the path prefix entry.

**Comment by matildepark** [comment]
Can you elaborate the question?

**Comment by sigilante** [comment]
Currently, searching "beak" does not yield any hits even though it occurs in the text in at least one entry ("path prefix").

**Comment by matildepark** [comment]
You can add any number of glossary entries for the same page. The path prefix entry is just

```

[glossaryEntry."path prefix"]
name = "path prefix"
symbol = ""
usage = "arvo"
desc = "The first three elements of a Clay file path denoting ship, desk and case (revision number)."
```

In that page’s toml. So you’d add another below it that says “beak” where it says “path prefix”.
