### ISSUE TITLE
`=>` renders to arrow

### ISSUE THREAD

**Issue by hosted-fornet** [urbit/developers.urbit.org#254]
On https://developers.urbit.org/reference/hoon/rune/tis rendered from /content/reference/hoon/rune/tis.md the `=>` section renders to a right-pointing arrow:

![221207-tisgar](https://user-images.githubusercontent.com/79381743/206273918-f60d1500-2b0e-4dc5-a563-8f36e9e48bf4.png)

**Comment by sigilante** [comment]
@gordoncc @matildepark I've noticed this too:  is there any OpenType setting or something we can do to turn this off?

**Comment by gordoncc** [comment]
@sigilante looks like that's a standard contextual font variant for Inter.  we can turn it off with the css property: "font-variant: none;"

Is this the only place with this issue or should we do this site-wide for body copy?

**Comment by gordoncc** [comment]
addressed in https://github.com/urbit/developers.urbit.org/commit/5df32003f6e988e04550301cbab2a54f3b2b8e3d
