### ISSUE TITLE
clay examples images have old `%home` desk rather than `%base`

### ISSUE THREAD

**Issue by hosted-fornet** [urbit/developers.urbit.org#255]
https://github.com/urbit/developers.urbit.org/blob/main/content/reference/arvo/clay/examples.md images all refer to the `%home` desk instead of the new name for it -- `%base`.

E.g.:
![stop-sub](https://user-images.githubusercontent.com/79381743/206301632-d2aef36e-2393-4968-915b-d0db0936f6fd.png)

**Comment by sigilante** [comment]
The vintage desk terminology is how you know we're authentic.

(Fixing)

**Comment by sigilante** [comment]
Fixed, may take a few minutes to propagate.
