### ISSUE TITLE
Rune pages hard to select in nav pane

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/developers.urbit.org#257]
When using `reference/hoon/rune` as a reference, at least one person (me), finds it difficult to select the rune family he wants.

The titles of the rune pages are shown in the following custom order in the nav pane:

```
Atoms and strings
Nock . ('dot')
Wild ! ('zap')
Change Subject = ('tis')
Conditionals ? ('wut')
Cores | ('bar')
Arms + ('lus')
Cells : ('col')
Calls % ('cen')
Casts ^ ('ket')
Structures $ ('buc')
Make ; ('mic')
Hints ~ ('sig')
Imports / ('fas')
Terminators -- and ==
```

Selecting a rune family is hard. The titles are not alphabetized, and the character associated with the family is lost in the middle of the line somewhere.

I propose either to move the character to the front:

`% Calls ('cen')`

or alphabetize the list, and volunteer to submit one of these solutions.

**Comment by sigilante** [comment]
Closing with #259 merge.
