### ISSUE TITLE
Cheat sheet describes `+*` as "produce a type constructor arm"

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/developers.urbit.org#258]
Is that accurate?

**Comment by sigilante** [comment]
It's likely a copy-paste error since that's really `+$` lusbuc.

https://developers.urbit.org/reference/hoon/rune/lus#-lustar

**Comment by sigilante** [comment]
Resolved here.

https://github.com/urbit/developers.urbit.org/blob/main/content/reference/hoon/cheat-sheet.md
