### ISSUE TITLE
Two /lib/csv/hoon files

### ISSUE THREAD

**Issue by sigilante** [urbit/developers.urbit.org#288]
In the docs for the `csv` mark example, a `/lib/csv/hoon` file is presented.

It is completely different from the `/lib/csv/hoon` file shipped with `%base`.

We need to either rename it, merge these gracefully, or advise people to not work on `%base` for that tutorial.

**Comment by philipcmonk** [comment]
Sounds like two were created independently.  I can give background on the one in base: I had a thread that I was using to extract ethereum data and export it as csv for some internal Tlon purposes.  I didn't know of any csv library, so I wrote one, and this was pre sw distribution, so I just added it to base.  Tlon doesn't need this anymore though, so feel free to move or change that at your all's discretion.

I don't know anyone else who uses it, though I've pointed a couple people at it, so they might.
