### ISSUE TITLE
search improvement: selecting a search term should take you to the anchor link

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/developers.urbit.org#289]
When I search something on developers.urbit.org, such as a rune--`wutlus`/`?+`--and hit enter, it takes me to the page and then I have to scroll to the correct header.

To replicate:
1. On developers.urbit.org, open the search menu with `cmd + k`
2. Type in `wutlus`
3. Hit enter to select the option for the `?+` rune.
<img width="822" alt="image" src="https://user-images.githubusercontent.com/82244264/217637559-b19277bf-3aff-4478-9ca3-532d94224688.png">
4. See how you are taken to the top of the `?` runes page and then manually scroll down to the `?+` header.

*Proposed Improvement*
Would be great for the search selection to take you to the anchor link for the specified rune/header section.

**Comment by thelifeandtimes** [comment]
Just discovered that this works as expected when searching from urbit.org, but then the anchor links don't appear if searching once you are already on developers.urbit.org.

**Comment by jalehman** [comment]
Good find. This should be an easy fix -- something is probably missing from the implementation in d.u.o.
