### ISSUE TITLE
Possible error in rune documentation for `|$` ?

### ISSUE THREAD

**Issue by tamlut-modnys** [urbit/developers.urbit.org#294]
I was studying the definition of a `wind` on the [App School 1 cards page](https://developers.urbit.org/guides/core/app-school/5-cards), and looked at the [reference for](https://developers.urbit.org/reference/hoon/rune/bar#-barbuc) `|$` to try and understand better. However, the `|$` definition doesn't seem to match its usage in `wind`. In particular, the following section, where it says `a` is a `lest` and `b` is a structure built from elements of `a`:

> |$ is used to declare a wet gate mold builder that is polymorphic in its input molds. a is a lest of term used as identifiers for the input molds. b is a structure built from elements of a. The output of |$ is a mold builder obtained by substituting the input molds parameterized by a into b.

[Relevant github page](https://github.com/urbit/developers.urbit.org/blob/bcd8328bcd5b4d043856fee080deada7c62b4687/content/reference/hoon/rune/bar.md)

@sigilante @tinnus-napbus

**Comment by sigilante** [comment]
We do have many runes that accept a `list` type (like `:~`) that handle adding the terminal `~` in desugaring.  The definition of `%brbc` is a little dense but it's doing the same thing, so the sample isn't explicitly a `lest`, it becomes one in the first pass of building the rune AST.

```
    [%brbc sample=(lest term) body=spec]                ::  |$  
```

When this is parsed, the rune children are handled using `++exqe`, which automatically turns the sample into a list of names:

```
      ++  exqe  |.(;~(goop lynx loan))                    ::  list of names then spec                   
```

So by the time the sample is processed, it has already acquired list-type:

```
        [%brbc *]  =-  ?~  -  !!                                                                      
                         :+  %brtr                              
                           [%bccl -]
                         |-
                         ?.  ?=([%gist *] body.gen)
                           [%ktcl body.gen]
                         [%note p.body.gen $(body.gen q.body.gen)]
                     %+  turn  `(list term)`sample.gen             
                     |=  =term
                     ^-  spec
                     =/  tar  [%base %noun]
                     [%bcts term [%bcsg tar [%bchp tar tar]]]
```

(The `%gist` is doccords handling.)

Does this help?

**Comment by sigilante** [comment]
Longer-form explanation:

The [`|$` barbuc](https://developers.urbit.org/reference/hoon/rune/bar#-barbuc) rune is used to build a mold builder gate.  (As such, it's fairly abstract.)  Essentially, it is sugar for a certain use of [`|*` bartar](https://developers.urbit.org/reference/hoon/rune/bar#-bartar):

```hoon
|$  [a b]
body

|*  [a=$~(* $-(* *)) b=$~(* $-(* *))]
^:
body
```

The formal AST for `%brbc` is `[%brbc sample=(lest term) body=spec]`.  How is this actually built?

Let's look at the sample first.  The sample is a `(lest term)`, or a non-empty list of identifiers.  Notice, however, that the actual value passed in (like `[a b]`) is _not_ a list at all.  Several runes that accept a `list` type (like `:~` colsig) handle adding the terminal `~` in the first parsing step.

The definition of `%brbc` is a little dense but it's doing the same thing, so the sample isn't explicitly a `lest` but becomes one in the first pass of building the rune AST.

In `hoon.hoon`, find the following line:

```
[%brbc sample=(lest term) body=spec]                ::  |$  
```

Next, find where it is parsed in `+vast`, the main parsing core.  This will tell you how the rune children are parsed.

```hoon
++  expression
  %-  stew
  ^.  stet  ^.  limo
  :~  :-  '|'
        ;~  pfix  bar
          %-  stew
          ^.  stet  ^.  limo                                
          :~  ['$' (rune buc %brbc exqe)]
          ==                                              
        ==
  ==
```

In this case, the rune children are handled using `+exqe`, which automatically turns the sample into a list of names:

```hoon
++  exqe  |.(;~(goop lynx loan))                    ::  list of names then spec                   
```

In this expression, there are three new names:

1. `+goop` is a separated `list` with doccord compatible docs included.
2. `+lynx` is a parser for `a` or `[a b c]` or `a  b  c  ==`.
3. `+loan` parses a `spec`.

So by the time the sample is processed, it has already acquired `list`-type from `++exqe`.

Next, let's look at the direct handling of the result of `+exqe`:

```hoon
[%brbc *]  =-  ?~  -  !!                                                                      
                 :+  %brtr                              
                   [%bccl -]
                 |-
                 ?.  ?=([%gist *] body.gen)
                   [%ktcl body.gen]
                 [%note p.body.gen $(body.gen q.body.gen)]
             %+  turn  `(list term)`sample.gen             
             |=  =term
             ^-  spec
             =/  tar  [%base %noun]
             [%bcts term [%bcsg tar [%bchp tar tar]]]
```

Desugared and annotated:

```hoon
=+  ::  first parse the sample into a lest
    %+  turn  `(list term)`sample.gen
    |=  =term  ^-  spec
    [%bcts term [%bcsg [%base %noun] [%bchp [%base %noun] [%base %noun]]]]
    ::
    ::  if the foregoing turned list is empty, crash
    ?~  -  !!
    ::  otherwise, produce the desugared |*
    :+  %brtr
      ::  this is the cell of the sample in the first arm
      [%bccl -]
    |-
    ?:  ?=([%gist *] body.gen)
      ::  if it's a gist, then include the doccords note
      [%note p.body.gen $(body.gen q.body.gen)]
    ::  otherwise just include the body
    [%ktcl body.gen]
```

Look for the structure:

```hoon
|*  [a=$~(* $-(* *)) b=$~(* $-(* *))]
^:
body
```
