### ISSUE TITLE
Broken Links on https://developers.urbit.org/guides/additional/software-distribution#deskdocket-0

### ISSUE THREAD

**Issue by datryn-ribdun** [urbit/developers.urbit.org#42]
All the `glob` related links seem to be broken (404). Not sure where they should even be pointing to.

Besides this one issue, is there any way to check for all link/image validity in a linting step? Don't know what tooling exists, but it would certainly be helpful.

**Comment by matildepark** [comment]
Related: urbit/urbit.org#1499

We'd probably have to write a function ourselves and run it on build (or, idk, put it in CI). It's striking to me that this is not a common thing for Next.js projects already.
